# Generated by Django 4.1.4 on 2023-01-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("manager", "Manager"), ("user", "User")], default="user", max_length=7
            ),
        ),
    ]
